In [1]:
import pandas as pd
datos=pd.DataFrame({"producto":["Manzana","Pan","Leche","huevos","Naranja"],
                   "precio":[1000,1200,5000,1800,1000],
                   "stock":[80,100,50,40,20]})
datos

  producto  precio  stock
0  Manzana    1000     80
1      Pan    1200    100
2    Leche    5000     50
3   huevos    1800     40
4  Naranja    1000     20

In [7]:
datos.head()

  producto  precio  stock
0  Manzana    1000     80
1      Pan    1200    100
2    Leche    5000     50
3   huevos    1800     40
4  Naranja    1000     20

In [8]:
datos.tail()

  producto  precio  stock
0  Manzana    1000     80
1      Pan    1200    100
2    Leche    5000     50
3   huevos    1800     40
4  Naranja    1000     20

In [9]:
datos.shape

(5, 3)

In [10]:
datos.dtypes

producto      str
precio      int64
stock       int64
dtype: object

In [11]:
datos["precio"]

0    1000
1    1200
2    5000
3    1800
4    1000
Name: precio, dtype: int64

In [13]:
datos[["precio", "producto"]]

   precio producto
0    1000  Manzana
1    1200      Pan
2    5000    Leche
3    1800   huevos
4    1000  Naranja

In [14]:
datos.loc[0]

producto    Manzana
precio         1000
stock            80
Name: 0, dtype: object

In [15]:
datos.loc[1:3]

  producto  precio  stock
1      Pan    1200    100
2    Leche    5000     50
3   huevos    1800     40

In [16]:
datos.iloc[0]

producto    Manzana
precio         1000
stock            80
Name: 0, dtype: object

In [17]:
datos.loc[0:2, "producto"]

0    Manzana
1        Pan
2      Leche
Name: producto, dtype: str

In [18]:
datos.loc[0:2, ["producto", "precio"]]

  producto  precio
0  Manzana    1000
1      Pan    1200
2    Leche    5000

In [22]:
datos[datos["precio"]>1000]

  producto  precio  stock
1      Pan    1200    100
2    Leche    5000     50
3   huevos    1800     40

In [23]:
datos[(datos["precio"]>1000) & (datos["stock"]<50)]

  producto  precio  stock
3   huevos    1800     40

In [25]:
datos["valor_total"] = datos["precio"] * datos["stock"]
datos

  producto  precio  stock  valor_total
0  Manzana    1000     80        80000
1      Pan    1200    100       120000
2    Leche    5000     50       250000
3   huevos    1800     40        72000
4  Naranja    1000     20        20000

In [26]:
datos["ciudad"] = "Barranquilla"
datos

  producto  precio  stock  valor_total        ciudad
0  Manzana    1000     80        80000  Barranquilla
1      Pan    1200    100       120000  Barranquilla
2    Leche    5000     50       250000  Barranquilla
3   huevos    1800     40        72000  Barranquilla
4  Naranja    1000     20        20000  Barranquilla

In [28]:
datos.loc[0, "precio"] = 13500
datos

  producto  precio  stock  valor_total        ciudad
0  Manzana   13500     80        80000  Barranquilla
1      Pan    1200    100       120000  Barranquilla
2    Leche    5000     50       250000  Barranquilla
3   huevos    1800     40        72000  Barranquilla
4  Naranja    1000     20        20000  Barranquilla

In [30]:
datos.loc[1, "stock"] = 80
datos

  producto  precio  stock  valor_total        ciudad
0  Manzana   13500     80        80000  Barranquilla
1      Pan    1200     80       120000  Barranquilla
2    Leche    5000     50       250000  Barranquilla
3   huevos    1800     40        72000  Barranquilla
4  Naranja    1000     20        20000  Barranquilla

In [ ]:
datos.drop(columns="ciudad", inplace=True)

In [35]:
datos

  producto  precio  stock  valor_total
0  Manzana   13500     80        80000
1      Pan    1200     80       120000
2    Leche    5000     50       250000
3   huevos    1800     40        72000
4  Naranja    1000     20        20000

In [36]:
datos["descuento"]= datos["valor_total"]*0.10

In [37]:
datos

  producto  precio  stock  valor_total  descuento
0  Manzana   13500     80        80000     8000.0
1      Pan    1200     80       120000    12000.0
2    Leche    5000     50       250000    25000.0
3   huevos    1800     40        72000     7200.0
4  Naranja    1000     20        20000     2000.0

In [38]:
datos.drop(columns="descuento")

  producto  precio  stock  valor_total
0  Manzana   13500     80        80000
1      Pan    1200     80       120000
2    Leche    5000     50       250000
3   huevos    1800     40        72000
4  Naranja    1000     20        20000

In [39]:
datos["IVA"] = datos["valor_total"]*0.19

In [40]:
datos

  producto  precio  stock  valor_total  descuento      IVA
0  Manzana   13500     80        80000     8000.0  15200.0
1      Pan    1200     80       120000    12000.0  22800.0
2    Leche    5000     50       250000    25000.0  47500.0
3   huevos    1800     40        72000     7200.0  13680.0
4  Naranja    1000     20        20000     2000.0   3800.0

In [41]:
datos = datos.drop(columns="IVA")

In [42]:
datos.isnull().sum()

producto       0
precio         0
stock          0
valor_total    0
descuento      0
dtype: int64

In [43]:
datos.rename(columns={"precio":"precio_unidad"})

  producto  precio_unidad  stock  valor_total  descuento
0  Manzana          13500     80        80000     8000.0
1      Pan           1200     80       120000    12000.0
2    Leche           5000     50       250000    25000.0
3   huevos           1800     40        72000     7200.0
4  Naranja           1000     20        20000     2000.0

In [45]:
datos[(datos["producto"]=="Manzana")| (datos["producto"]=="huevos")]

  producto  precio  stock  valor_total  descuento
0  Manzana   13500     80        80000     8000.0
3   huevos    1800     40        72000     7200.0

In [47]:
datos[((datos["producto"] == "Manzana")| (datos["producto"] == "huevos")) & (datos["valor_total"]>75000)]

  producto  precio  stock  valor_total  descuento
0  Manzana   13500     80        80000     8000.0

In [49]:
datos[~((datos["producto"] == "Naranja") | (datos["producto"] == "Leche"))]

  producto  precio  stock  valor_total  descuento
0  Manzana   13500     80        80000     8000.0
1      Pan    1200     80       120000    12000.0
3   huevos    1800     40        72000     7200.0

In [51]:
datos.query("precio > 1000")

  producto  precio  stock  valor_total  descuento
0  Manzana   13500     80        80000     8000.0
1      Pan    1200     80       120000    12000.0
2    Leche    5000     50       250000    25000.0
3   huevos    1800     40        72000     7200.0

In [52]:
df = datos.rename(columns={"precio":"Precio_unidad"})

In [53]:
df.query("Precio_unidad <20000 | producto == 'Manzana'")

  producto  Precio_unidad  stock  valor_total  descuento
0  Manzana          13500     80        80000     8000.0
1      Pan           1200     80       120000    12000.0
2    Leche           5000     50       250000    25000.0
3   huevos           1800     40        72000     7200.0
4  Naranja           1000     20        20000     2000.0

In [54]:
df.sort_values("Precio_unidad", ascending=False)

  producto  Precio_unidad  stock  valor_total  descuento
0  Manzana          13500     80        80000     8000.0
2    Leche           5000     50       250000    25000.0
3   huevos           1800     40        72000     7200.0
1      Pan           1200     80       120000    12000.0
4  Naranja           1000     20        20000     2000.0